---
title: "ClearedvsNon-cleared"
author: "Fay Lindfield-Butler"
date: "2025-04-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Load commonly used packages
```{r}
library(readxl)
library(pheatmap)
library(dendextend)
library(ggplot2)
library(readxl)
library(dplyr)
library(tibble)
```


# Cleared vs Exposed
```{r}
HBcrAg <- read_excel("/Users/faylindfield/Documents/Project_Delta/Data/HBV monoinfected cohort clinical data and HDV BLV positive.xlsx", sheet = "Sheet1")

HBcrAg_plot <- ggplot(HBcrAg, aes(x = Group, y = Value, fill = Group)) +
  geom_boxplot(width = 0.3) +
  geom_jitter(position = position_jitterdodge(dodge.width = 0, jitter.width = 0), color = "black", alpha = 0.7) +
  labs(title = "", x = "", y = "HBsAg quant [IU/ml]") +
  theme_minimal() +
  theme(
    legend.position = "none", 
    plot.title = element_text(face = "bold"), 
    axis.title.x = element_text(face = "bold"),  
    axis.title.y = element_text(face = "bold")) +
  scale_fill_manual(values =  c("slategray1", "steelblue4"))
print(HBcrAg_plot)

ggsave("avsc_HBcrAg.png", HBcrAg_plot , width = 4, height = 4)
```





#1. HBcrAg
```{r}
HBcrAg <- read_excel("/Users/faylindfield/Documents/Project_Delta/Data/CLvsN.xlsx", sheet = "Sheet1")

HBcrAg_plot <- ggplot(HBcrAg, aes(x = Group, y = Value, fill = Group)) +
  geom_boxplot(width = 0.3) +
  geom_jitter(position = position_jitterdodge(dodge.width = 0, jitter.width = 0), color = "black", alpha = 0.7) +
  labs(title = "", x = "HDV", y = "HBsAg quant [IU/ml]") +
  theme_minimal() +
  theme(
    legend.position = "none", 
    plot.title = element_text(face = "bold"), 
    axis.title.x = element_text(face = "bold"),  
    axis.title.y = element_text(face = "bold")) +
  scale_fill_manual(values =  c("steelblue4", "slategray1"))
print(HBcrAg_plot)

ggsave("avsc_HBcrAg.png", HBcrAg_plot , width = 4, height = 4)

```

#HBcrAg
```{r}
RNA <- c(3.61E+05, 3.06E+05, 5.92E+04, 6.77E+04, 4.74E+04, 5.27E+04, 1.78E+04, 5.73E+05, 6.40E+04, 4.90E+06, 1.80E+03, 6.47E+04, 3.82E+06, 2.45E+05, 1.07E+05, 5.26E+06, 3.43E+04, 1.08E+03, 6.66E+04, 7.28E+02, 2.13E+03, 2.47E+05, 2.12E+04, 2.33E+04, 2.33E+03, 6.17E+04, 6.64E+03, 3.24E+04, 6.98E+02, 4.03E+04, 2.33E+03, 4.57E+06, 6.66E+04, 2.23E+04, 3.19E+03, 5.28E+03, 5.57E+04, 1.23E+03, 1.43E+03, 4.92E+05, 1.39E+05, 5.65E+05, 7.22E+04, 1.23E+06, 3.22E+04, 1.20E+05)
Biomarker <- c(3.8, 4.2, 3.8, 4.4, 3.1, 4.3, 3.9, 5.1, 3.3, 6.8, 3.5, 5.2, 4.7, 3.4, 3.3, 6.3, 3.6, 4, 3.3, 4.7, 5.2, 3.4, 3.1, 3, 3.1, 3.4, 2.6, 2.9, 3.6, 2.9, 2.9, 6.5, 2.9, 3.5, 3.8, 4.5, 5.3, 3.5, 3.9, 3.6, 3.3, 3.6, 4.8, 3.9, 3.5, 3.1)
stat_Biomarker <- cor(RNA, Biomarker, method = "pearson")
print(stat_Biomarker)
RNA_pgRNA_data <- cbind(RNA, Biomarker)

corr_plot <- ggplot(RNA_pgRNA_data, aes(x = RNA, y = Biomarker)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE, col = "steelblue4") +
  labs(title = "", x = "Log 10 HDV RNA local [copies/ml]", y = "HBcrAg [log10 U/ml]") +
  annotate("text", x = min(RNA), y = max(Biomarker), 
           label = paste("Pearson r =", round(stat_Biomarker, 2)), 
           color = "steelblue4", size = 5, hjust = -1) +
  theme_minimal()
ggsave("RNAHBcrAg.png",corr_plot , width = 6, height = 4)
```

#2. HBsAg
```{r}
RNA <- c(3.61E+05, 3.06E+05, 5.92E+04, 6.77E+04, 4.74E+04, 5.27E+04, 1.78E+04, 5.73E+05, 6.40E+04, 4.90E+06, 6.47E+04, 1.70E+07, 3.82E+06, 2.45E+05, 1.07E+05, 5.26E+06, 3.43E+04, 1.08E+03, 6.66E+04, 7.28E+02, 2.13E+03, 2.47E+05, 2.12E+04, 2.33E+04, 2.33E+03, 6.17E+04, 6.48E+02,  6.98E+02, 4.03E+04, 2.33E+03, 4.57E+06, 6.66E+04, 2.23E+04, 3.19E+03, 5.28E+03, 3.09E+07,  5.57E+04, 1.23E+03, 1.43E+03, 1.39E+05, 3.24E+04, 5.65E+05, 7.22E+04, 1.23E+06, 3.22E+04, 1.20E+05)
Biomarker <- c(9060, 4418, 4025, 5590, 1801, 27192, 20076, 23333, 999, 14912, 1350, 13599, 10374, 22045, 2350, 10702, 2838, 1328, 1804, 8068, 8584, 3673, 1203, 516, 0.73, 12287, 1.55, 0.1, 4039, 1149, 23419, 11773, 9954, 122, 14.35, 30907,  2224, 2304, 1280,8227, 12850, 14546, 10285, 15460, 4984, 8999)
stat_Biomarker <- cor(RNA, Biomarker, method = "pearson")
print(stat_Biomarker)
RNA_pgRNA_data <- cbind(RNA, Biomarker)

corr_plot <- ggplot(RNA_pgRNA_data, aes(x = RNA, y = Biomarker)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE, col = "steelblue4") +
  labs(title = "", x = "Log 10 HDV RNA local [copies/ml]", y = "HBsAg quant [IU/ml]") +
  annotate("text", x = min(RNA), y = max(Biomarker), 
           label = paste("Pearson r =", round(stat_Biomarker, 2)), 
           color = "steelblue4", size = 5, hjust = -1) +
  theme_minimal()
plot(corr_plot)
ggsave("RNAHBcrAg.png",corr_plot , width = 6, height = 4)
```

#3. pgRNA
```{r}
RNA <- c(3.61E+05, 3.06E+05, 5.92E+04, 6.77E+04, 4.74E+04, 5.27E+04, 1.78E+04, 5.73E+05, 6.40E+04, 4.90E+06, 1.80E+03, 6.47E+04, 1.70E+07, 3.82E+06, 2.45E+05, 1.07E+05, 3.43E+04, 1.08E+03, 6.66E+04, 7.28E+02,  2.47E+05, 2.33E+04, 6.17E+04,  6.48E+02, 3.24E+04, 6.98E+02, 4.03E+04, 2.33E+03, 4.57E+06, 6.66E+04, 2.23E+04, 3.19E+03, 5.28E+03, 3.09E+07, 3.29E+07, 5.57E+04, 1.23E+03, 1.43E+03, 4.92E+05, 1.39E+05, 5.65E+05, 7.22E+04, 1.23E+06, 3.22E+04, 1.20E+05)
Biomarker <- c(1.9, 2.66, 1.99, 3.27, 1.65, 3.57, 2.15, 2.26, 1.65, 4.27, 3.92, 1.99, 2.57, 1.99, 2.66, 1.67,  1.65, 2.22,  2.61, 2.77, 1.65, 3.02, 1.89, 1.71, 2.16, 1.71, 1.67, 1.8, 1.88, 1.8, 1.65, 2.19, 2.65, 2.77, 4.28, 1.65, 1.98, 2.09, 3.96, 1.82,  1.65, 3.02, 2.88, 4.11, 1.68)
stat_Biomarker <- cor(RNA, Biomarker, method = "pearson")
print(stat_Biomarker)
RNA_pgRNA_data <- cbind(RNA, Biomarker)

corr_plot <- ggplot(RNA_pgRNA_data, aes(x = RNA, y = Biomarker)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE, col = "steelblue4") +
  labs(title = "", x = "Log 10 HDV RNA local [copies/ml]", y = "pgRNA [log10 U/ml]") +
  annotate("text", x = min(RNA), y = max(Biomarker), 
           label = paste("Pearson r =", round(stat_Biomarker, 2)), 
           color = "steelblue4", size = 5, hjust = -1) +
  theme_minimal()
plot(corr_plot)
ggsave("RNAHBcrAg.png",corr_plot , width = 6, height = 4)
```